# Generated by Django 4.2.1 on 2023-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_assessment', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=3)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
